version: '3'

services:
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - ./redis/data/:/data
  
  flask-gif-server:
    depends_on:
      - redis
    build:
      context: ./
    ports:
      - 8000:8000
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
